id: A8CFFFA7A
base_file: f0B5E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:12:40.953142
  last_modified_at: 2022-06-17 14:12:40.953154
