id: A8CFFFA7A
base_file: f5376.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:12:40.961366
  last_modified_at: 2022-06-17 14:12:40.961377
